-- =========================================
-- ENUM für Reaction-Typen
-- =========================================
create type public.reaction_type as enum (
  'like',
  'funny',
  'wow',
  'fire'
);

-- =========================================
-- Tabelle: post_reactions
-- =========================================
create table public.post_reactions (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  reaction public.reaction_type not null,
  created_at timestamp with time zone default now()
);

-- =========================================
-- Ein User darf nur 1 Reaction pro Post haben
-- =========================================
create unique index post_reactions_unique_user_post
on public.post_reactions (post_id, user_id);

-- =========================================
-- Index für Performance
-- =========================================
create index post_reactions_post_id_idx
on public.post_reactions (post_id);

-- =========================================
-- RLS aktivieren
-- =========================================
alter table public.post_reactions enable row level security;

-- =========================================
-- Policy: Lesen erlaubt für alle
-- =========================================
create policy "Allow read access"
on public.post_reactions
for select
using (true);

-- =========================================
-- Policy: Nur eingeloggte User dürfen schreiben
-- =========================================
create policy "Allow insert for authenticated users"
on public.post_reactions
for insert
with check (auth.uid() = user_id);

-- =========================================
-- Policy: User darf eigene Reaction ändern/löschen
-- =========================================
create policy "Allow update own reaction"
on public.post_reactions
for update
using (auth.uid() = user_id);

create policy "Allow delete own reaction"
on public.post_reactions
for delete
using (auth.uid() = user_id);