create table public.comment_reactions (
  id bigint generated by default as identity primary key,
  comment_id bigint not null references public.comments(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  reaction public.reaction_type not null,
  created_at timestamp with time zone default now()
);

create unique index comment_reactions_unique_user_comment
on public.comment_reactions (comment_id, user_id);

create index comment_reactions_comment_id_idx
on public.comment_reactions (comment_id);

alter table public.comment_reactions enable row level security;

create policy "Allow read access for comment reactions"
on public.comment_reactions
for select
using (true);

create policy "Allow insert own comment reaction"
on public.comment_reactions
for insert
with check (auth.uid() = user_id);

create policy "Allow update own comment reaction"
on public.comment_reactions
for update
using (auth.uid() = user_id);

create policy "Allow delete own comment reaction"
on public.comment_reactions
for delete
using (auth.uid() = user_id);